export default {
  DESIGN_IDEA_PROMPT:
    "Imagine you're a logo designer tasked with crafting a unique and memorable logo for a brand named {logoTitle}. The brand's description is: {logoDesc}. Based on description, brainstorm creative scenarios and concepts for the elements of the logo. Use your full, creative imagination. The tone should be {logoTone}. Brainstorm 9 distinct logo ideas, each summarised in a phrase (7-11 words). These ideas should be very easily understood. So much so, that even a toddler would understand what the ideas you are suggesting. No fancy or complicated wording, keep it dead-simple. The elements can be humans, animal, non-living, anything really. Also, very important: Don't describe the logo, describe what's happening in your own imaginative concept you have come up with. Deliver the ideas as 'ideas':[] in JSON format",
  LOGO_PROMPT_ORG:
    "Generate a text prompt for logo for the brand '{logoTitle}' that includes only the icon. The result you generate should NOT have any typography, text, character, word. It should purely be the logo. In no case should the logo be ALL WHITE. The brand is described as {logoDesc}. The logo should be designed in the {logoDesign} style, drawing inspiration from {logoPrompt}, and should embody the concept of {logoIdea}. Use the color palette {logoColor} for the design. The logo should have a {logoSimplicity} aesthetic, and the logo's tone should be {logoTone}. Give me result in JSON format with prompt field only. The prompt should be strictly under 2000 characters",

  LOGO_PROMPT:
    "Generate a text prompt for logo icon for a brand/company. The prompt should be as detailed as possible. The colors should look distinct if they were on a white background. It should have atlease 3 colors. The brand is described as {logoDesc}. The logo should be designed in the {logoDesign} style, drawing inspiration from {logoPrompt}, and should embody the concept of {logoIdea}. Use the color palette {logoColor} for the design. The logo's tone should be {logoTone}. It should not be an overly-simple logo. Give me result in JSON format with prompt field only. The prompt should be strictly under 1500 characters",
};
